---
title: "Methoder"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(officer)
library(flextable)
invisible(source(file = "r/PrepDefinitions.R"))
```

### Definition af sygdomme, procedurer of medicin

Data er udtrukket fra registrene ved hjælp af koder (ICD-10-koder for sygdomme, procedurekoder for behandlinger, ATC-koder for medicin). Herunder er alle de viste sygdomme, procedurer og typer hjertemedicin specificeret i form af deres respektive koder samt hvilke registre, data er hentet fra.


```{r definitions-codes, echo=FALSE}
diag_pretty <-
  lapply(diag_list, function(i)
    i[1, .(desc_dk, code_simple, diag_type, pat_type)]) %>%
  rbindlist()

out_pretty <- flextable(diag_pretty) %>%
  width(j = "desc_dk", width = 2.5) %>%
  width(j = "code_simple", width = 3.0) %>%
  height_all(height = 0.55) %>%
  align() %>%
  align(part = "header") %>%
  fontsize(size = 16, part = "header") %>% 
  bold(part = "header") %>% 
  set_header_labels(desc_dk = "Sygdomme",
                    code_simple = "ICD-kode",
                    diag_type = "Diagnose type",
                    pat_type = "Indlægelse type")
out_pretty
                    
```
