---
title: "Revising HjeteTal"
author: "Matthew Phelps"
date: "April 10, 2018"
output: html_document
---
***

### Registries
* Landspatientregisteret (LPR)
    + Diagnosis
    + inddto
    + uddto
* Dødesårsagsregisteret
* Det Centrale Personregister (BEFK)
    + OPR_LAND - country of origin
    + FOED_DAG - date of birth
    + KOEN - sex -
    + bef_year (check variable for accuracy)
* Uddannelsesregisteret
* Lægemiddelstatikregisteret


### Forkammerflimren - Current functionality

#### Current variables

 * Nye tilfælde 
 * Antal tilfælde I alt 
 * Dødelighed
 * Ambulante besøg
 * Indlæggelser 
 * Genindlæggelser
 * Sengedage 
 * 1-års overlevelse 
 * 5-års overlevelse
 
 Data ranges from 2006 - 2015
 
#### Current Presentation of data
* Disaggregation available by **age**, **education**, **ethnicity**, **Region**, and **year**.
* For each type of disaggregation:
    + Bar charts (line chart for time-series) are given in **age-standardized rates per 100,000 people**.
    + Data table showing **absolute numbers** and **age-standardized rates per 100,000 by sex**.
* Additional documentation on methods available on separate webpages 
    
### Limitations
* Does not include data for anyone under 35
* No description of variables or of illness/diagnosis (i.e. what is Forkammerflimren?)
* No ability to download data tables
* No linkage to medication data
* No map display for geographic coverage
* Geographic resolution limited to Regions (instead of f.x. Kommunes)
* Limited ways to interact with data
* Slow to load
* User options not immediately apparent
* Predetermined survival ranges
* Non-standardized rates are not available
* Difficult to get overview accross heart diseases
* No ability for users to give feedback
* Source code is not open source (or at least not easily accessible)
* Lack of methedological transparency

### Goals
* Flexibility - mix and match metrics and diseases
* Intuitiveness
* Clarity
* Protection from wrong interpretation
* Methedological transparency (and open source code)


### Ideas for new metrics/analysis?
* Mean age at first diagnosis
* Connection to mental health outcomes

