app <- ShinyDriver$new("../../")
app$snapshotInit("CVDtest_1")

app$snapshot(list(output = "rate_count_desc"))
app$snapshot(list(output = "variable_desc"))
app$snapshot(list(output = "d3_plot_line_html"))
app$setInputs(data_vis_tabs = "Tabels")
app$snapshot(list(output = "table_counts"))
app$setInputs(varCVD = "v8")
app$setInputs(varCVD = "v13")
app$snapshot(list(output = "table1_title"))
app$snapshot(list(output = "table_counts"))
app$snapshot(list(output = "table2_title"))
app$snapshot(list(output = "table_rates"))
app$snapshot(list(output = "count_desc"))
app$snapshot(list(output = "variable_desc"))
