---
title: "HjerteTal 2 feature selection"

date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---
***

#### Date range
Data ranging from 2006 - 2015

<br>

#### Registries
* **Landspatientregisteret (LPR)**
    + Diagnosis
    + inddto
    + uddto
    + diagtype
    + pattype
    + sengedage
    + ambdto (besøgsdato)
    + operations (opr - operationskode from t_sksopr)
    + behandling (opr - operationskode from t_sksube)
* **Dødsårsagsregisteret**
    + Dødsårsager
    + Dødsdato
    + Bopælskommune
* **Det Centrale Personregister (BEFK)**
    + OPR_LAND - country of origin
    + FOED_DAG - date of birth
    + KOEN - sex -
    + bef_year (check variable for accuracy)
* **Uddannelsesregisteret**
* **Lægemiddelstatikregisteret**
    + ATC
    + EKSD

<br>

#### Current variables

* **Incidence**  
    + Defined as the number of new diseases in a given disease within a given period of time in a given population.  A person's first illness case is considered a new / incident if he / she has not been diagnosed with the same cardiovascular disease diagnosis within the last 10 years.
        - *Case count*
        - *Age-specific rate (per 100,000 people)*
        - *Age-standardized rate (per 100,000 people)*
 
* **Prevalence**
    + Defined as the number of people in a particular population living at a certain time with cardiovascular disease as of 1 January each year. A person is considered to be prevalent if he / she has had at least one case of the specified disease within the last 10 calendar years.
        - *Case count*
        - *Age-specific rate (per 100,000)*
        - *Age-standardized rate (per 100,000)*
        
* **Dødelighed**
    + Defined as the number of people who die during a year of a given cardiovascular disease.
        - *Case count*
        - *Age-specific rate (per 100,000)*
        - *Age-standardized rate (per 100,000)*
    
* **30 day mortality**
    + Defined based on whether a person dies for any reason within 30 days. The at-risk population is anyone who was diagnosed with, or received the specified illness/treatment. A death is defined as the person dying within 30 days of either the incident or following the given procedure. If there are more procedures within the same year, see only the first one.
        - *Count*
        - *Age-specific percentage (of those at-risk)*
        - *Age-standardized percentage (of those at-risk)*
* **1-year mortality**
    + Defined based on whether a person dies for any reason within 365 days.The at-risk population is anyone who was diagnosed with, or received the specified illness/treatment. A death is defined as the person dying within 365 days of either the incident or following the given procedure. If there are more procedures within the same year, see only the first one.
        - *Count*
        - *Age-specific percentage (of those at-risk)*
        - *Age-standardized percentage (of those at-risk)*
* **5-year mortality**
    + Defined based on whether a person dies for any reason within 1825 days. The at-risk population is anyone who was diagnosed with, or received the specified illness/treatment. A death is defined as the person dying within 1825 days of either the incident or following the given procedure. If there are more procedures within the same year, see only the first one. 
        - *Count*
        - *Age-specific percentage (of those at-risk)*
        - *Age-standardized percentage (of those at-risk)*
* **Indlæggelser** 
    + Defined as hospitalization with a given cardiovascular disease such as action diagnosis (or bi-diagnosis of the ventricle flare and heart failure). Transfer to another department within the same day is considered as extension of the initial hospitalization, regardless of cause. 
        - *Number of hospitalizations*
        - *Number of patients admitted*
        - *Cost (in 1,000 DKK)*
        - *Age-specific hospitalization rate (per 100,000)*
        - *Age standardized hospitalization rate (per 100,000)*

* **30-day Genindlæggelser**
    + Defined as a new hospitalization, regardless of diagnosis, maximum 30 days after the last hospitalization with a cardiovascular disease among persons who have been hospitalized with the cardiovascular disease.
        - *Number of re-admissions*
        - *Number of re-admitted patients (because single patient may be re-admitted multiple times)*
        - *Percentage of patients with original diagnosis re-admitted*
        
* **Sengedage**
    + Defined as the number of bed days for patients with a given cardiovascular disease.
        - *Number of days*
        - *Average number of days per hospitalization*
* **Ambulatory visits**
    + Defined as the number of visits that are part of an outpatient course of cardiovascular disease as action diagnosis (or bi-diagnosis of the ventricle flare and heart failure). There are visits from both completed and unfinished outpatient courses.
        - *Number of outpatient visits*
        - *Number of outpatient patients*
        - *Age-specific rate (per 100,000 persons)*
        - *Age-standardized rate (per 100,000 persons)*


 #### General exclusion parameters
 
 People are removed from the population (including the at-risk population) if they meet any of the following critera:
 
 * No bef_year data
 * No birthdare data
 * No education data
 
 For each year, a person can be excluded if:
 
 * They did not reside in DK as of 1. January of the given year
 * 
 <br><br>
 
#### Current Presentation of data
* Disaggregation available by **age**, **education**, **ethnicity**, **Region**, and **year**.
* For each type of disaggregation:
    + Bar charts (line chart for time-series) are given in **age-standardized rates per 100,000 people**.
    + Data table showing **absolute numbers** and **age-standardized rates per 100,000 by sex**.
* Additional documentation on methods available on separate webpages 
    
### Limitations
* Does not include data for anyone under 35
* No description of variables or of illness/diagnosis (i.e. what is Forkammerflimren?)
* No ability to download data tables
* No linkage to medication data
* No map display for geographic coverage
* Geographic resolution limited to Regions (instead of f.x. Kommunes)
* Limited ways to interact with data
* Slow to load
* User options not immediately apparent
* Predetermined survival ranges
* Non-standardized rates are not available
* Difficult to get overview accross heart diseases
* No ability for users to give feedback
* Source code is not open source (or at least not easily accessible)
* Lack of methedological transparency

### Goals
* Flexibility - mix and match metrics and diseases
* Intuitiveness
* Clarity
* Protection from wrong interpretation
* Methedological transparency (and open source code)


### Ideas for new metrics/analysis?
* Mean age at first diagnosis
* Connection to mental health outcomes

