---
title: "Barsel wish list"
output: html_document
---


1. Gunnar and Maja (and Matthew, if available) to meet with SIF. Meeting to address:
    + Potential to extend current HjerteTal web platform until spring 2020 (with no updating of data)
    + Ask questions found in the SIF questions document
2. Internal HjerteTal working group to be established and meeting scheduled for sometime after 1. Okt
3. Process for importing new datasets into our DST projects is underway. Christian Torp-Pedersen is adding raw datasets to project 6322 (and/or to 6818), but this is a long process and may require requesting permission from Sundhedsdatastyrelsen. Gunnar is supposed to follow-up with Christian Torp-Pedersen in week 32. Follow+up with Gunnar in week 33 to make sure we do not need to do anything from our end. The datasets to be added include:
    + BEF
    + FAIN
    + t_addresse_hist
    + t_person
    + t_adresse_udland
    + t_adresse_udland_hist
4. Web-analytics: what resolution is needed (i.e. simply who visited the site, or who clicked which buttons)